name: 同步代码

on:
  push:
    branches: [ master,dev ]

jobs:
  gitlink:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: gitlink
        uses: wearerequired/git-mirror-action@master #同步至 gitlink
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          destination-repo: "git@code.gitlink.org.cn:lengleng/pig.git"

      - name: gitee
        uses: wearerequired/git-mirror-action@master #同步至 gitlink
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          destination-repo: "git@gitee.com:log4j/pig.git"
